### PR TITLE
[WIP] Docker images

### PR DESCRIPTION
**Pull request by klud1**
## Dockerfile Integration #3

Just started to work with the docker images.

### TODO

* [x] Dockerfiles for the other architectures
* [x] Automation scripts for building the images

* [x] Possible changes to `config.json` file
  * [x] Can be filled dynamically using env vars.
    * [x] ~~Use a fixed to the json file, so it can be a volume to persist config~~.
  * [x] Not using `config.json` at all, and use dynamic values (now using optional configuration)
    * [x] ~Values declared in CLI with flags instead. (e.g. `docker run url-shortener --clientID 'XXX' --clientSecret 'YYY' --baseUrl 'http://domain.com'` and so on)~
    * [ ] Values in json file can be declared using env vars instead (e.g. `docker run -e CLIENTID="XXX" -e CLIENTSECRET="YYY" -e BASEURL="http://domain.com" url-shortener` and so on)
* [x] Fixed or default path to database, so it can be a volume to persist data. (Same approach as with config.json can be used). Now you can set a directory in which the stuff is stored. The config file is now optional, you can work with environment variables.

### Related Issues

- [x] #2 Provide Dockerimage on the Dockerhub
- [x] #3 Create Dockerfile

### Depends on

- [x] #36

### CODE REVIEW

**Comment by maxibanki** [comment]
Hello,

It probably makes sense to switch from the normal `json.Decode/Encode` in Go to something with more features like [viper](https://github.com/spf13/viper). It has e.g. support for overriding config values by priority. So environment variable will override the values from the config.json and so on, see [here](https://github.com/spf13/viper#why-viper) for more information.

For the building, I would have imagined that they would always be rebuilt by Source. Maybe the build steps could be:

- build frontend
- build Go binary
- run binary

So that the size of the last build step is really small, because of the very less dependencies of a Go binary.

**Comment by klud1** [comment]
Sure, will take a look at it, one more thing in order to get a small binary, it could be statically built, at least for the Docker image, that'd result in a really small footprint image (either based on scratch or alpine)

**Comment by maxibanki** [comment]
The binaries already embed the frontend and the templates, in my opinion they are already really small (tar.bz2 ~4-5mb). If you mean that with statically built.

**Comment by maxibanki** [comment]
Hi,

I've updated the configuration, so that we can use environment variables easily. For usage check out the [wiki](https://github.com/maxibanki/golang-url-shortener/wiki/Configuration).

**Comment by klud1** [comment]
@maxibanki thanks for the great news, will take a look at the changes asap, i have free time on weekends mostly.

and about the docker images, sure! Although I'm not familiar with Travis CI, a GitLab CI user here,  guess i can learn easily.

**Comment by maxibanki** [comment]
@klud1 sorry for my not very professional behavior towards you and excuse me for having built the dockerfile myself. However, I would like to thank you very much for the ideas and the proposal on how this should be implemented.

**Pull request closed without merging**
